"use client";

import { useEffect, useState } from "react";
import { Card, EmptyHint, Loading } from "@/components/ui";
import { getJson, postJson, type FaqRow, type TicketRow } from "@/lib/api";

export default function FaqPage() {
  const [faqs, setFaqs] = useState<FaqRow[] | null>(null);
  const [tickets, setTickets] = useState<TicketRow[]>([]);
  const [generating, setGenerating] = useState(false);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const load = () => {
    Promise.all([
      getJson<{ faqs: FaqRow[] }>("/api/faq"),
      getJson<{ tickets: TicketRow[] }>("/api/tickets"),
    ])
      .then(([f, t]) => {
        setFaqs(f.faqs);
        setTickets(t.tickets);
      })
      .catch((e) => setError(String(e)))
      .finally(() => setLoading(false));
  };

  useEffect(load, []);

  const generate = async () => {
    setGenerating(true);
    setError(null);
    try {
      const res = await postJson<{ created: number; faqs: FaqRow[] }>("/api/faq", { max: 12 });
      setFaqs(res.faqs);
    } catch (e) {
      setError(String(e));
    } finally {
      setGenerating(false);
    }
  };

  return (
    <div className="space-y-4">
      <div className="flex flex-wrap items-end justify-between gap-3">
        <div>
          <h1 className="text-xl font-semibold text-white">Auto-FAQ & Escalation Queue</h1>
          <p className="mt-0.5 text-xs text-slate-500">
            FAQ generated by AI from real user questions (same language as users). Escalated copilot drafts land in the ticket queue below.
          </p>
        </div>
        <button
          onClick={generate}
          disabled={generating}
          className="rounded-md bg-sky-600 px-4 py-2 text-sm font-medium text-white hover:bg-sky-500 disabled:opacity-50"
        >
          {generating ? "Generating from real posts…" : "Regenerate FAQ"}
        </button>
      </div>

      {error && <div className="text-sm text-rose-300">Failed: {error}</div>}
      {loading && <Loading />}

      <Card title={`FAQ (${faqs?.length ?? 0})`}>
        {faqs && faqs.length === 0 && (
          <EmptyHint>No FAQ yet. Click “Regenerate FAQ” — it clusters real questions from collected mentions.</EmptyHint>
        )}
        <div className="space-y-2">
          {faqs?.map((f) => (
            <details key={f.id} className="rounded-md border border-slate-800 bg-slate-900/60 p-3">
              <summary className="cursor-pointer text-sm font-medium text-slate-200">
                {f.question}
                <span className="ml-2 rounded bg-slate-800 px-1.5 py-0.5 text-[10px] uppercase text-slate-400">{f.language ?? "?"}</span>
              </summary>
              <p className="mt-2 whitespace-pre-wrap text-xs leading-relaxed text-slate-400">{f.answer}</p>
              <div className="mt-1 text-[10px] text-slate-600">generated {f.created_at}</div>
            </details>
          ))}
        </div>
      </Card>

      <Card title={`Escalation tickets (${tickets.length})`}>
        {tickets.length === 0 && <EmptyHint>No tickets. Use “Draft reply” on the Search page, then escalate.</EmptyHint>}
        <div className="space-y-2">
          {tickets.map((t) => (
            <div key={t.id} className="rounded-md border border-slate-800 bg-slate-900/60 p-3 text-xs">
              <div className="mb-1 flex flex-wrap items-center gap-2">
                <span
                  className={`rounded border px-1.5 py-0.5 text-[10px] font-semibold uppercase ${
                    t.severity === "urgent" || t.severity === "high"
                      ? "border-rose-500 bg-rose-500/20 text-rose-300"
                      : "border-amber-500 bg-amber-500/15 text-amber-300"
                  }`}
                >
                  {t.severity}
                </span>
                <span className="text-slate-500">
                  ticket #{t.id} · item {t.item_id} · {t.country ?? "?"} · {t.created_at} · {t.status}
                </span>
              </div>
              {t.content_preview && <p className="line-clamp-2 italic text-slate-400">“{t.content_preview}”</p>}
              {t.draft && <p className="mt-1 line-clamp-3 text-slate-300">{t.draft}</p>}
            </div>
          ))}
        </div>
      </Card>
    </div>
  );
}
